### ISSUE TITLE
Save user events

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#160]
If the user is unknown, save the event anonymously

**Comment by psandboge** [comment]
Eventen ska va detaljerade nog så att man t ex kan spela upp en spelsession igen, utan tillgång till appen eller data utanför eventstreamen. Jag hade tänkt mig en serie exposure-events (alla event inklusive timestamp förstås), med typ av exposure, fråga svarsalternativ, osv, action-events, klickade på knapp x.
Sedan behövs någon form av filter, så man kan minska datavolymerna om det behövs (t ex på gratis heroku...) Den har pucken går nog att dela upp i ganska många deluppgifter...

**Comment by grebdevs** [comment]
Kanske kan Redux hjälpa?
