### ISSUE TITLE
Lyssna på events för att hålla reda på en användares progress

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#191]
Vi behöver en ny tabell med användare, nugget, antal rätta svara, fel svar och tidpunkt för senaste svar och rätt/fel för just det svaret. Skapa en ny post om användaren exponeras för ett nytt ord. Uppdatera annars bara för svarsevent.

**Comment by Changis** [comment]
fundera över grupp-id för att koppla ihop events.
