### ISSUE TITLE
Undersök deploymentalternativ

### ISSUE THREAD

**Issue by Changis** [kits-ab/gakusei#196]

**Comment by grebdevs** [comment]
Azure, Amazon, annat

**Comment by Changis** [comment]
Docker?

**Comment by psandboge** [comment]
Jag har en lightsail-instans igång. Just nu pekar jp.sandboge.se dit. Det är en nginx framför spring-boot-appen. Ingen postgres är konfad ännu, så det H2-varianten som körs.
