### ISSUE TITLE
Smycka ut landingpage

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#220]
Lektioner man har börjat på, statistik och annat nyttigt

**Comment by wbern** [comment]
Har lagt detta i UserStatisticsPage, behövs lite designbeslut för vad som ska finnas på landing page tänker jag.

![uploads/5ed41586-4454-48f6-98ea-e7c38ae212d2/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5ed41586-4454-48f6-98ea-e7c38ae212d2%2Fblob)
