### ISSUE TITLE
Ordna backup-rutin (Diskussion behövs)

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#265]

**Comment by wbern** [comment]
Backup-funktionalitet finns nu i form av ett bash skript på lightsail-maskinerna, men backup är enbart lokal på maskinen. Finns inte heller något schemalagt för att köra den. Att ta upp på nästa demo.

**Comment by wbern** [comment]
Löst via cron-jobs på båda lightsail-servrar
