### ISSUE TITLE
Flashcards

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#278]
Virtuella kort med japansk writing på ena sidan och svenska på andra sidan och reading på tredje sidan och engelska på fjärde sidan. Och gärna möjlighet att välja vilka sidor som ska visas, och ordning.

**Comment by wbern** [comment]
Nästan klar

**Comment by wbern** [comment]
![uploads/b9d31994-513d-4cd5-9afa-70fd6b87100f/Flash Cards.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb9d31994-513d-4cd5-9afa-70fd6b87100f%2FFlash+Cards.gif)

**Comment by wbern** [comment]
b1906239af7eb5e8e00c368f12344da36d23597d
5bff33c7bb27b81096c4e5975a202c75ba854786
