### ISSUE TITLE
Ta hänsyn till ordklass när man genererar frågor

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#283]
Frågor på noun, verb och adjective ska ha samma ordklass som svarsalternativ. Övriga ordklasser kan fortsätta vara helt slumpvisa (jag har ofta varit osäker på ordklass här, så det går inte att lita på klassificeringen). Om det finns för få alternativ av en viss ordklass, välj slumpvis.

**Comment by wbern** [comment]
Förutsätter att vi ändå kör på ordklassen som "bästa tillgängliga" tills vidare?

**Comment by wbern** [comment]
ac4678811a1f7f001b0902034854cd175b1bd262
