### ISSUE TITLE
Release 1.0.4 (förr 1.0.2)

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#298]

**Comment by wbern** [comment]
@psandboge Denna borde heta 1.0.3, släppte en som 1.0.2 precis

**Comment by wbern** [comment]
Släppte en hotfix-1.0.3 för att korrigera ful bit text (det stod "Om Gakusei!!" i utloggat läge från när jag gjort tester).

**Comment by wbern** [comment]
Eftersom jag förstod det som att grammatik-sidan önskades snarast så pushade jag 1.0.4 så fort jag hade det på plats.
