### ISSUE TITLE
react redux issue

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#300]
William Bernting [8:46 PM] 
Något mysko med sidan igen. Får ta en ordentlig titt på måndag.

Pierre Sandboge [8:48 PM] 
Ok, det fungerar för mig vad jag kan se. Vad är det som är mysko? (edited)

William Bernting [8:49 PM] 
Dirigerar mig till play/guess direkt och sidan är blank

Pierre Sandboge [8:51 PM] 
Ok, låter skumt. Men det kan vänta till måndag...

William Bernting [8:51 PM] 
Clearade cache, sen funkade det. Då är det något som React redux har för sig

[8:52]  
Jag löser det nog relativt fort på måndag.

Pierre Sandboge [8:52 PM] 
Bara du kan reproducera det så

**Comment by wbern** [comment]
Login-sidan som inte redirectade om man redan var inloggad.
