### ISSUE TITLE
Bugg: blank sida

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#310]
js/main_biúndle.js : "An error occured trying to load the resource." (Enligt Safari)

Samma fel i Chrome och Firefox.

<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>gakusei</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/custom.css">
    <link rel="icon" type="image/png" href="/icons/favicon-32x32.png" sizes="32x32">
</head>
<body>
<div id="index_root"></div>
<script type="text/javascript" src="js/main_bundle.js"></script>
</body>
</html>

**Comment by wbern** [comment]
Måste vara att routing reducern rehydratar pathen man är på. Får kolla imorgon.
