### ISSUE TITLE
Lägg in enkel variant av kanjitest

### ISSUE THREAD

**Issue by psandboge** [kits-ab/gakusei#341]
https://psandboge.github.io/japan/k1200a.html

**Comment by wbern** [comment]
![uploads/b88cbe08-81d6-49ab-b1d5-ff5885f99c78/DrawingKanji1.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb88cbe08-81d6-49ab-b1d5-ff5885f99c78%2FDrawingKanji1.gif)
