### ISSUE TITLE
[Avbruten] Lägg in scaling för det man ritar när korrekta tecknet ej syns

### ISSUE THREAD

**Issue by wbern** [kits-ab/gakusei#376]
Liten utmaning rent matematiskt, men borde inte ta lång tid.

**Comment by wbern** [comment]
Eftersom användaren inte har någon utgångspunkt för var han eller hon ska börja rita tecknet så behövs detta.

**Comment by wbern** [comment]
Byte av designval. För när svarslinjerna ej syns så visas istället ett tecken längst upp till vänster.

**Comment by psandboge** [comment]
Inte aktuell längre
