### ISSUE TITLE
GUI: Första sidan

### ISSUE THREAD

**Issue by mjdubell** [kits-ab/gakusei#381]
Förslag på innehåll:

* Information om gakusei
* Lära sig Japanska
* Varför gakusei är bra
    * Svenska
* Skärmdumpar på appen
* Användare är anonyma (förklara)
* Funkar på mobila enheter

Max tre dagar arbete.

**Comment by DzenoBa** [comment]
https://github.com/kits-ab/gakusei/pull/387
