### ISSUE TITLE
Optimera bygge att prioritera byggtid frontend / backend

### ISSUE THREAD

**Issue by mjdubell** [kits-ab/gakusei#382]
* Spring-dev-tools
* Två miljöer: Dev och Prod
    * Dev kanske inte behöver ladda in resurser som bara används i prod.

**Comment by Doverstav** [comment]
Spring-dev-tools finns i projektet. Den kollar på classpathen, och om den upptäcker ändringar kompilerar den om just dessa ändringar. Så istället för att starta om hela applikation vid gjorda ändringar kan man bygga om den, vilket automatiskt triggar en kortare restart som tar ca 3 sekunder.

Orkar man inte refresha webbläsaren själv så kan man installera en extension till sin webbläsare, [LiveReload](http://livereload.com/). För mer info om spring dev tools, se [här](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html).
