### ISSUE TITLE
Gakusei: Importera quiz från datalistor.

### ISSUE THREAD

**Issue by DzenoBa** [kits-ab/gakusei#400]
Hantera req från client sidan
* Controller-n ska kunna ta emot en list med quiz.
* Spara allt i listan i DB.
* Spara filen? För att compare-a.

Detta skall vara i Gakusei-admin.

**Comment by mjdubell** [comment]
Fixat i https://github.com/kits-ab/gakusei-admin/commit/5868a98434a3a9a076e5105da471e379e16d7024
