### ISSUE TITLE
Gakusei: Produktionssättning

### ISSUE THREAD

**Issue by Doverstav** [kits-ab/gakusei#437]
- [x] fixa användare + ssh-nycklar
- [x] stänga av root-inloggning och lösenords-autentisering
- [x] postgresql
- [x] nginx
- [x] node
- [x] kopiera deploy-script från staging
- [x] genomföra produktionssättning
- [x] peka om gakusei.daigaku.se
- [x] fixa ssl

### Guide till produktionssättning
1. Töm databasen
Ta bort alla tabeller i public och contentschema, ta även bort själva contentschemat
`sudo su - postgres`
`psql -U gakusei`
`SET search_path TO contentschema, public;`
`DROP TABLE books, courses, facts, incorrect_answers, lessons, lessons_nuggets, nuggets, prerequisites, quiz, quiz_nugget, word_types, databasechangelog, databasechangeloglock, events, progresstrackinglist, user_lesson, users CASCADE;`
`DROP SCHEMA contentschema;`
`\q`
`exit`

2. Återskapa produktionsdatabasen från sql-filen.
`psql -U gakusei < <sql_file>`

3. Undersök om det finns duplicerad data i user_lesson.
`psql -U gakusei`
`select * from user_lesson;`
Om så är fallet, ta bort den duplicerade datan och inserta igen.
tex
`DELETE FROM public.user_lesson WHERE user_ref = <x> AND lesson_ref = <y>;`
`INSERT INTO public.user_lesson (user_ref, lesson_ref) VALUES (<x>, <y>);`
`\q`
`exit`

4. Kopiera gakusei.production.jar till gakusei.production.jar.to.deploy
`sudo su production` och navigera till `production/`
`cp gakusei.production.jar gakusei.production.jar.to.deploy`

5. Ta bort gamla backups och loggar.
`rm -r backups`
`rm deploy-watcher.log`

6. Kör deploy-scriptet
`sh Scripts/deploy_gakusei.sh`

**Comment by psandboge** [comment]
Done
