### ISSUE TITLE
create datamodel / database model

### ISSUE THREAD

**Issue by Changis** [kits-ab/gakusei#5]

**Comment by grebdevs** [comment]
![uploads/b8d33d95-0e9a-4927-82c9-553f8336ac53/gakusei_db.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb8d33d95-0e9a-4927-82c9-553f8336ac53%2Fgakusei_db.png)

**Comment by grebdevs** [comment]
@Changis looks into creating implementation in database/entities
